import type { WebsiteCategory } from '@/onboarding/profile'

/**
 * Matches a template's stored category against the fixed list the app
 * actually offers, tolerant of the ways that value can drift: extra
 * whitespace, mixed case, or a common misspelling ("Eduction" for
 * "Education") from a template that was typed or generated by hand rather
 * than picked from the dropdown.
 *
 * Every template in this codebase already stores a clean, lowercase,
 * canonical value — this exists as a safety net so a category typo in a
 * template added later hides that template from its category instead of
 * silently failing to match, which is what the bug report described.
 */
const TYPOS: Record<string, WebsiteCategory> = {
  eduction: 'education',
  educaton: 'education',
  educational: 'education',
  school: 'education',
  coaching: 'education',
  restaurant: 'food',
  dining: 'food',
  fooddining: 'food',
  salon: 'beauty',
  spa: 'beauty',
  gym: 'fitness',
  sports: 'fitness',
  clinic: 'health',
  medical: 'health',
  property: 'realestate',
  'real-estate': 'realestate',
  realestates: 'realestate',
  construction: 'home-services',
  homeservices: 'home-services',
  business: 'professional',
  agency: 'professional',
}

/** The clean, lowercase form a category value is compared in. */
function fold(value: string): string {
  return value.trim().toLowerCase().replace(/[\s_]+/g, '-')
}

/**
 * The canonical category a stored value maps to, or the folded value itself
 * if it does not match anything known — so an unrecognised category still
 * compares consistently rather than being silently dropped.
 */
export function normalizeCategory(value: string | null | undefined): string {
  if (!value) return ''
  const folded = fold(value)
  const compact = folded.replace(/-/g, '')
  return TYPOS[folded] ?? TYPOS[compact] ?? folded
}

/** Whether a template's category matches the category a user picked, tolerant of drift in either value. */
export function categoryMatches(templateCategory: string | null | undefined, wanted: string | null | undefined): boolean {
  const a = normalizeCategory(templateCategory)
  const b = normalizeCategory(wanted)
  // Two unset categories are not "the same category" — the caller already has
  // its own way to mean "show everything" (an explicit 'all'), so nothing
  // here should silently fall back to matching every uncategorised template.
  return a !== '' && a === b
}
