import type { BlockType } from '@/blocks/types'

// Generated by scripts/analyse-widget-datasets.py from reviewed basic-use mappings.
// Search hints only: never use to convert saved blocks or enable source controls.
export const widgetSearchAliases = {
  "banner": [
    "Announcement Bar"
  ],
  "contact": [
    "Contact Form"
  ],
  "cta": [
    "Call To Action",
    "Call to Action",
    "EA Call to Action"
  ],
  "divider": [
    "Divider",
    "Spacer"
  ],
  "faq": [
    "Accordion",
    "FAQ"
  ],
  "features": [
    "EA Feature List",
    "Feature Grid"
  ],
  "gallery": [
    "Basic Gallery",
    "Gallery"
  ],
  "hero": [
    "Hero"
  ],
  "hours": [
    "Business Hours"
  ],
  "image": [
    "Image"
  ],
  "logocloud": [
    "Logo Cloud"
  ],
  "map": [
    "Google Maps",
    "Map"
  ],
  "navbar": [
    "EA Simple Menu",
    "Nav Menu",
    "Navbar"
  ],
  "newsletter": [
    "Newsletter"
  ],
  "pricing": [
    "EA Pricing Table",
    "Price Table",
    "Pricing Table"
  ],
  "products": [
    "EA Price Menu",
    "EA Static Product",
    "Price List"
  ],
  "slider": [
    "Image Carousel",
    "Slides"
  ],
  "stats": [
    "Counter",
    "Stats"
  ],
  "team": [
    "EA Team Members",
    "Team Members"
  ],
  "testimonials": [
    "EA Testimonials",
    "Testimonial"
  ],
  "video": [
    "Video"
  ]
} as const satisfies Partial<Record<BlockType, readonly string[]>>
