import { test, expect, openBlankEditor, reloadEditor } from './fixtures'

test.use({ actionTimeout: 15000 })

test('clicking the visible button selects its settings without navigating', async ({ page }) => {
  await openBlankEditor(page)
  const canvas = page.getByRole('region', { name: /Site preview/ })
  await page.getByRole('button', { name: 'Widgets', exact: true }).first().click()
  await page.getByPlaceholder('Search 200+ widgets...').fill('Button')
  await page.getByRole('button', { name: 'Button', exact: true }).first().click()
  await canvas.locator('h1').first().click()
  await canvas.getByRole('link', { name: 'Get in touch', exact: true }).last().click()
  await expect(page.getByLabel('Button text', { exact: true })).toBeVisible()
  await expect(canvas.locator('h1').first()).toBeVisible()
  await page.getByLabel('Button text', { exact:true }).fill('Book a visit')
  await page.getByLabel('Link type').selectOption('email')
  await page.getByLabel('Link destination').fill('hello@example.com')
  await expect(canvas.getByRole('link', { name:'Book a visit',exact:true })).toHaveAttribute('href','mailto:hello@example.com')
})

test('Hero buttons have independent text, links, responsive styles and saved history', async ({page}) => {
  await openBlankEditor(page)
  const canvas=page.getByRole('region',{name:/Site preview/})
  const primary=canvas.locator('[data-element="primaryCta"]').first()
  const secondary=canvas.locator('[data-element="secondaryCta"]').first()
  const beforeSecondary=await secondary.textContent()
  await primary.locator('svg').click()
  await expect(page.getByRole('heading',{name:'Primary Button',exact:true})).toBeVisible()
  await page.getByLabel('Button text',{exact:true}).fill('Explore our story')
  await page.getByLabel('Link type').selectOption('page')
  await page.getByLabel('Destination page').selectOption({label:'Contact'})
  await expect(primary).toHaveAttribute('href','/contact')
  await expect(secondary).toHaveText(beforeSecondary!)
  await page.getByRole('button',{name:'Style',exact:true}).click()
  await page.getByLabel('Button colour',{exact:true}).fill('#123456')
  await expect(primary).toHaveCSS('background-color','rgb(18, 52, 86)')
  await page.screenshot({path:'test-results/button-inspector.png',fullPage:true})
  await page.getByRole('heading',{name:'Primary Button',exact:true}).click()
  await page.keyboard.press('Control+z')
  await expect(primary).not.toHaveCSS('background-color','rgb(18, 52, 86)')
  await page.keyboard.press('Control+Shift+z')
  await expect(primary).toHaveCSS('background-color','rgb(18, 52, 86)')
  await page.getByRole('button',{name:'Mobile',exact:true}).click()
  const saved=page.waitForResponse(r=>r.request().method()==='PUT' && /\/api\/sites\/[^/]+$/.test(new URL(r.url()).pathname) && r.ok())
  await page.getByLabel('Font size',{exact:true}).fill('19')
  await saved
  await expect(primary).toHaveCSS('font-size','19px')
  await page.getByRole('button',{name:'Desktop',exact:true}).click()
  await expect(primary).not.toHaveCSS('font-size','19px')
  await secondary.click()
  await expect(page.getByRole('heading',{name:'Secondary Button',exact:true})).toBeVisible()
  await page.getByLabel('Button text',{exact:true}).fill('Call our team')
  await page.getByLabel('Link type').selectOption('phone')
  const savedSecondary=page.waitForResponse(r=>r.request().method()==='PUT' && /\/api\/sites\/[^/]+$/.test(new URL(r.url()).pathname) && r.ok())
  await page.getByLabel('Link destination').fill('+1234567890')
  await savedSecondary
  await reloadEditor(page)
  await expect(primary).toContainText('Explore our story')
  await expect(primary).toHaveAttribute('href','/contact')
  await expect(primary).toHaveCSS('background-color','rgb(18, 52, 86)')
  await expect(secondary).toHaveAttribute('href','tel:+1234567890')
  const homeHeading=await canvas.locator('h1').first().textContent()
  await page.getByRole('button',{name:'Toggle preview mode'}).click()
  await primary.click()
  await expect(canvas.locator('h1,h2').first()).not.toHaveText(homeHeading!)
  await expect(canvas.locator('[data-element-selected]')).toHaveCount(0)
  await page.getByRole('button',{name:'Toggle preview mode'}).click()
})

test('navigation, CTA, heading and image edits are reachable from the canvas', async ({page}) => {
  await openBlankEditor(page)
  const canvas=page.getByRole('region',{name:/Site preview/})
  const heading=canvas.locator('h1').first()
  const original=await heading.textContent()
  await canvas.locator('nav').getByRole('link',{name:'Contact',exact:true}).first().click()
  await expect(heading).toHaveText(original!)
  await expect(page.getByRole('heading',{name:'Navigation Link',exact:true})).toBeVisible()
  await expect(page.getByLabel('Destination page')).toHaveValue(/.+/)
  await heading.dblclick()
  await heading.fill('Edited on the page')
  await heading.press('Enter')
  await expect(page.getByLabel('Heading',{exact:true})).toHaveValue('Edited on the page')
  const photo=canvas.locator('img[data-image="image"]').first()
  await photo.click()
  await expect(page.getByLabel('Replace image')).toBeVisible()
  const replacement='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="100" height="100"%3E%3Crect width="100" height="100" fill="red"/%3E%3C/svg%3E'
  await page.getByLabel('Replace image').fill(replacement)
  await expect(photo).toHaveAttribute('src',replacement)
  await page.getByRole('button',{name:'Widgets',exact:true}).first().click()
  await page.getByPlaceholder('Search 200+ widgets...').fill('Call to Action')
  await page.getByRole('button',{name:'Call to Action',exact:true}).first().click()
  const cta=canvas.locator('[data-element="buttonText"]').first()
  await cta.click()
  await expect(page.getByRole('heading',{name:'CTA Button',exact:true})).toBeVisible()
  await page.getByLabel('Button text',{exact:true}).fill('Send an enquiry')
  await page.getByLabel('Link type').selectOption('page')
  await page.getByLabel('Destination page').selectOption({label:'Contact'})
  await expect(cta).toHaveAttribute('href','/contact')
  const footer=canvas.locator('footer [data-edit="copyright"]').first()
  await footer.dblclick()
  await footer.fill('Copyright Editing Test')
  await footer.press('Enter')
  // The panel calls this field "Copyright line"; the widget schema is what
  // names it, and the test has to ask for the name a person would read.
  await expect(page.getByLabel('Copyright line',{exact:true})).toHaveValue('Copyright Editing Test')
})
