import type { Field, NumberField, RepeaterItemField, SelectField, TextareaField, TextField, WidgetSchema } from './field-types'

export type AdditionalWidgetType = 'heading' | 'button' | 'rich-text' | 'icon' | 'icon-box' | 'image-box' | 'social-icons' | 'list' | 'progress' | 'tabs' | 'accordion' | 'html-embed' | 'spacer' | 'quote' | 'badge' | 'code-block' | 'table' | 'steps' | 'audio' | 'back-to-top'
export interface AdditionalWidgetDefinition {
  type: AdditionalWidgetType; label: string; description: string; category: string
  variants: string[]; defaultProps: Record<string, unknown>; fields: Record<string, Field>
}
const text = (label: string): TextField => ({ kind: 'text', label })
const area = (label: string): TextareaField => ({ kind: 'textarea', label, rows: 5 })
const number = (label: string, min: number, max: number): NumberField => ({ kind: 'number', label, min, max })
const select = (label: string, values: string[]): SelectField => ({ kind: 'select', label, options: values.map(value => ({ value, label: value })) })
const items = (fields: Record<string, RepeaterItemField>): Field => ({ kind: 'repeater', label: 'Items', addLabel: 'Add item', titleKey: 'title', fields })
const actionFields = { label: text('Button text'), url: text('Page or website address') }
export const additionalWidgets: AdditionalWidgetDefinition[] = [
  { type: 'heading', label: 'Heading', description: 'Standalone heading with H1–H6 levels', category: 'Basic', variants: ['default'], defaultProps: { text: 'Welcome to our business', level: 'h2', align: 'left' }, fields: { text: text('Heading text'), level: select('Heading level', ['h1','h2','h3','h4','h5','h6']), align: select('Alignment', ['left','center','right']) } },
  { type: 'button', label: 'Button', description: 'A standalone button linking to a page or website', category: 'Basic', variants: ['solid','outline'], defaultProps: { label: 'Get in touch', url: 'Contact', align: 'left' }, fields: { ...actionFields, align: select('Alignment', ['left','center','right']) } },
  { type: 'rich-text', label: 'Rich Text', description: 'Formatted paragraphs, bold, italic, headings and lists', category: 'Basic', variants: ['default'], defaultProps: { body: '## Our story\nWe help **local businesses** grow.\n\n- Personal attention\n- Reliable service' }, fields: { body: { kind: 'richtext', label: 'Formatted content' } } },
  { type: 'icon', label: 'Icon', description: 'A standalone icon with a label and colour', category: 'Basic', variants: ['plain','circle'], defaultProps: { icon: 'Heart', label: 'Made with care', color: '#6366f1', size: 40 }, fields: { icon: text('Icon name'), label: text('Accessible label'), color: {kind:'color',label:'Icon colour'}, size: number('Icon size',16,128) } },
  { type: 'icon-box', label: 'Icon Box', description: 'An icon, heading, description and optional link', category: 'Content', variants: ['default'], defaultProps: { icon:'Shield',title:'Trusted service',body:'Friendly support from a team that cares.',label:'Learn more',url:'About' }, fields: { icon:text('Icon name'),title:text('Heading'),body:area('Description'),...actionFields } },
  { type: 'image-box', label: 'Image Box', description: 'An image card with heading, description and link', category: 'Content', variants: ['default'], defaultProps: { image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80',alt:'Bright workspace',title:'Our workspace',body:'A welcoming place to meet and work together.',label:'Explore',url:'About' }, fields: { image:{kind:'image',label:'Card image'},alt:text('Image description'),title:text('Heading'),body:area('Description'),...actionFields } },
  { type: 'social-icons', label: 'Social Icons', description: 'Social profile links with recognisable labels', category: 'Contact', variants: ['pills','plain'], defaultProps: { items:[{title:'Instagram',url:'https://instagram.com'},{title:'YouTube',url:'https://youtube.com'},{title:'LinkedIn',url:'https://linkedin.com'}] }, fields: { items:items({title:text('Platform name'),url:text('Profile address')}) } },
  { type: 'list', label: 'List', description: 'Bulleted or numbered content list', category: 'Content', variants: ['bullets','numbered'], defaultProps: { title:'Why choose us',items:['Clear communication','Personal attention','Reliable delivery'] }, fields: {title:text('Heading'),items:{kind:'strings',label:'List entries',addLabel:'Add entry'}} },
  { type: 'progress', label: 'Progress Bar', description: 'Labelled percentage progress indicator', category: 'Content', variants: ['default'], defaultProps: { title:'Project progress',value:75,color:'#6366f1' }, fields: {title:text('Label'),value:number('Percentage',0,100),color:{kind:'color',label:'Bar colour'}} },
  { type: 'tabs', label: 'Tabs', description: 'Switch between labelled content panels', category: 'Content', variants: ['default'], defaultProps: { items:[{title:'Overview',body:'Everything you need to get started.'},{title:'Details',body:'Our team will help you choose the right service.'},{title:'Support',body:'Contact us whenever you need a hand.'}] }, fields:{items:items({title:text('Tab title'),body:area('Tab content')})} },
  { type: 'accordion', label: 'Accordion', description: 'Expandable text panels', category:'Content',variants:['default'],defaultProps:{items:[{title:'How does it work?',body:'Tell us what you need and we will help you get started.'},{title:'Can I ask a question?',body:'Yes. Reach out through our contact page.'}]},fields:{items:items({title:text('Panel title'),body:area('Panel content')})} },
  { type:'html-embed',label:'HTML Embed',description:'Isolated HTML and CSS content in a sandboxed frame',category:'Advanced',variants:['default','original'],defaultProps:{title:'Custom content',html:'<div style="font:18px system-ui;padding:24px;background:#eef2ff;color:#312e81;border-radius:12px"><h2>Welcome</h2><p>Your custom HTML content goes here.</p></div>',height:240},fields:{title:text('Frame title'),html:{kind:'textarea',label:'HTML and CSS',rows:8,help:'Edit the HTML and CSS here. Original templates keep their theme scripts in an isolated frame; ordinary embeds disable scripts and forms.'},height:number('Frame height',80,1600)} },
  { type:'spacer',label:'Spacer',description:'Adjustable empty space between sections',category:'Layout',variants:['default'],defaultProps:{height:48},fields:{height:number('Space height',0,800)} },
  { type:'quote',label:'Quote',description:'A quotation with author attribution',category:'Content',variants:['default'],defaultProps:{quote:'Great work begins with listening.',author:'Our team'},fields:{quote:area('Quotation'),author:text('Author')} },
  { type:'badge',label:'Badge',description:'A compact status or announcement label',category:'Content',variants:['default'],defaultProps:{text:'New service',color:'#6366f1'},fields:{text:text('Badge text'),color:{kind:'color',label:'Badge colour'}} },
  { type:'code-block',label:'Code Block',description:'Code sample displayed as text, never executed',category:'Advanced',variants:['default'],defaultProps:{language:'JavaScript',code:'const message = "Hello, world!";\nconsole.log(message);'},fields:{language:text('Language label'),code:area('Code sample')} },
  { type:'table',label:'Table',description:'A scrollable comparison or information table',category:'Content',variants:['default'],defaultProps:{caption:'Service comparison',columns:['Service','Duration','Availability'],rows:[{title:'Consultation',cells:'30 minutes | Weekdays'},{title:'Project review',cells:'60 minutes | By appointment'}]},fields:{caption:text('Table caption'),columns:{kind:'strings',label:'Column headings',addLabel:'Add column'},rows:{kind:'repeater',label:'Table rows',addLabel:'Add row',titleKey:'title',help:'First cell is the row title. Separate remaining cells with |.',fields:{title:text('First cell'),cells:text('Remaining cells')}}} },
  { type:'steps',label:'Steps',description:'A numbered sequence explaining a process',category:'Content',variants:['default'],defaultProps:{items:[{title:'Tell us your needs',body:'Share your goals with our team.'},{title:'Choose a plan',body:'We agree on the work and timing.'},{title:'Get started',body:'We keep you informed at every step.'}]},fields:{items:items({title:text('Step title'),body:area('Step description')})} },
  { type:'audio',label:'Audio',description:'An audio player with native playback controls',category:'Media',variants:['default'],defaultProps:{title:'Listen to our introduction',src:'https://upload.wikimedia.org/wikipedia/commons/4/47/Beethoven_Moonlight_1st_movement.ogg'},fields:{title:text('Audio title'),src:text('Audio file address')} },
  { type:'back-to-top',label:'Back To Top',description:'A link returning visitors to the top of the page',category:'Navigation',variants:['default'],defaultProps:{label:'Back to top'},fields:{label:text('Link text')} },
]

export const additionalSchemas = Object.fromEntries(additionalWidgets.map(widget => [widget.type, {
  groups: [{ title: 'Content', fields: widget.fields }, ...(widget.variants.length > 1 ? [{ title:'Layout', fields:{variant:select('Style',widget.variants)} }] : [])],
}])) as Record<AdditionalWidgetType, WidgetSchema>
export const isAdditionalWidget = (type: string): type is AdditionalWidgetType => additionalWidgets.some(widget => widget.type === type)
