import type { Field, RepeaterItemField } from './field-types'

const labelFor = (key: string) => key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())
function fieldFor(key: string, value: unknown): Field {
  const label = labelFor(key)
  if (typeof value === 'boolean') return { kind: 'switch', label }
  if (typeof value === 'number') return { kind: 'number', label, min: -1000000, max: 1000000 }
  if (Array.isArray(value)) {
    if (value.every(item => typeof item === 'string')) return { kind: 'strings', label, addLabel: 'Add entry' }
    const sample = value[0] as Record<string, unknown> | undefined
    return { kind: 'repeater', label, addLabel:'Add item', titleKey: Object.keys(sample ?? {title:''})[0], fields: Object.fromEntries(Object.entries(sample ?? {title:''}).map(([k,v])=>[k,fieldFor(k,v) as RepeaterItemField])) }
  }
  if (/image|poster|avatar/i.test(key) && !/width|height|alt/i.test(key)) return { kind:'image',label }
  if (/body|description|content|html|code|json/i.test(key)) return { kind:'textarea',label,rows:4 }
  return { kind:'text',label, ...(key === 'endpoint' ? { help:'Your provider URL. Leave empty until connected. No successful submission is simulated.' } : {}) }
}
function widget<T extends string>(type:T,label:string,category:string,family:string,description:string,defaultProps:Record<string,unknown>) {
  return {type,label,category,family,description,defaultProps,variants:['default'],fields:Object.fromEntries(Object.entries(defaultProps).map(([k,v])=>[k,fieldFor(k,v)]))}
}
const article = { title:'A better way to work', body:'Practical ideas from our team.', image:'', url:'#article', category:'Guides', author:'Alex Morgan', date:'2026-09-15' }
const product = { productId:'product-1',title:'Everyday notebook',description:'A durable notebook for your best ideas.',image:'',price:24,currency:'USD',url:'#product' }
const linkItems = [{ title:'Overview',url:'#overview' },{title:'Services',url:'#services'},{title:'Contact',url:'#contact'}]
const cards = [{title:'Discovery',body:'Understand the goals and agree on a clear plan.',image:'',url:'#discovery'},{title:'Delivery',body:'Build, review and deliver the work together.',image:'',url:'#delivery'}]
const panels = [{title:'Overview',body:'Find the right solution for your team.'},{title:'Details',body:'Flexible options with personal support.'}]

export const expandedWidgets = [
  widget('paragraph','Paragraph','Basic','text','Plain semantic paragraph with editable copy.',{body:'Tell your visitors what makes your work special.'}),
  widget('icon-button','Icon Button','Basic','action','An accessible compact icon action with destination.',{label:'Explore',icon:'ArrowRight',url:'#services'}),
  widget('download-button','Download Button','Basic','action','Download a configured file using a filename hint.',{label:'Download brochure',url:'/brochure.pdf',filename:'brochure.pdf'}),
  widget('link','Link','Basic','action','Inline hyperlink with editable destination and title.',{label:'Read our story',url:'#about',newTab:false}),
  widget('label','Label','Basic','text','Label associated with a form control by its ID.',{text:'Your name',forId:'customer-name'}),
  widget('preformatted','Preformatted Text','Basic','text','Preserves whitespace and line breaks in plain text.',{body:'Line one\n    Indented line\nLine three'}),
  widget('highlight-text','Highlight Text','Basic','text','Highlights an editable phrase within a sentence.',{body:'Create something remarkable today.',highlight:'remarkable'}),
  widget('ordered-list','Ordered List','Basic','text','Numbered instructions with an editable start number.',{title:'Getting started',start:1,items:['Create your account','Choose a plan','Start your project']}),
  widget('icon-list','Icon List','Basic','text','Checklist with an icon for each editable entry.',{title:'Included',items:[{title:'Personal support',icon:'Check'},{title:'Regular updates',icon:'Check'}]}),
  widget('avatar','Avatar','Basic','text','Portrait with initials fallback and accessible name.',{name:'Alex Morgan',image:'',size:64}),
  widget('tooltip','Tooltip','Interactive','disclosure','Help text available on keyboard focus and pointer hover.',{label:'More information',body:'Your information stays private.'}),
  widget('alert','Alert','Basic','text','Semantic alert message with severity and optional dismissal.',{title:'Please review',body:'Check your details before continuing.',severity:'info',dismissible:true}),
  widget('notification','Notification','Interactive','disclosure','Trigger a dismissible live status notification.',{label:'Show notification',body:'Your local preview notification.',duration:5}),
  widget('circle-progress','Circle Progress','Basic','metric','Radial progress indicator with a numeric maximum.',{title:'Completion',value:65,max:100}),
  widget('animated-counter','Animated Counter','Basic','metric','Animate from zero to a numeric value with reduced-motion support.',{title:'Happy customers',value:1250,duration:2,prefix:'',suffix:'+'}),
  widget('star-rating','Star Rating','Basic','metric','Selectable rating with keyboard accessible radio controls.',{title:'Rate your experience',value:4,max:5,readonly:false}),
  widget('clipboard-button','Copy to Clipboard','Basic','action','Copies configured text and reports clipboard failures.',{label:'Copy reference',text:'REF-2026-001'}),
  widget('keyboard-shortcut','Keyboard Shortcut','Basic','text','Semantic keyboard key sequence with an explanation.',{title:'Save your work',keys:['Ctrl','S'],body:'Use this shortcut in your application.'}),

  widget('section','Section','Layout','layout','Semantic section landmark containing editable child widgets.',{title:'Section',gap:24}),
  widget('row','Row','Layout','layout','Horizontal child layout with wrapping on small screens.',{title:'Row',gap:20}),
  widget('column','Column','Layout','layout','Vertical child layout with adjustable spacing.',{title:'Column',gap:20}),
  widget('grid','Grid','Layout','layout','Explicit equal-width columns with responsive stacking.',{title:'Grid',columns:3,gap:20}),
  widget('auto-grid','Auto Grid','Layout','layout','Automatically fit columns to a minimum card width.',{title:'Auto grid',minCardWidth:240,gap:20}),
  widget('masonry-layout','Masonry Layout','Layout','layout','Variable-height children flow through CSS columns.',{title:'Masonry',columns:3,gap:20}),
  widget('split-layout','Split Layout','Layout','layout','Two unequal content areas with an editable split ratio.',{title:'Split layout',ratio:40,gap:24}),
  widget('sidebar-layout','Sidebar Layout','Layout','layout','Fixed-width sidebar alongside flexible main content.',{title:'Sidebar layout',sidebarWidth:240,gap:24}),
  widget('sticky-container','Sticky Container','Layout','layout','Child content sticks within its parent at a configured offset.',{title:'Sticky content',offset:16,gap:16}),
  widget('scroll-container','Scroll Container','Layout','layout','Scrollable child content with a bounded height.',{title:'Scrollable content',height:320,gap:16}),

  widget('dropdown-menu','Dropdown Menu','Navigation','navigation','Expandable link menu with Escape dismissal.',{title:'Explore',items:linkItems}),
  widget('mega-menu','Mega Menu','Navigation','navigation','Expandable multi-column links with group labels and descriptions.',{title:'Explore services',items:[{title:'Strategy',url:'#strategy',group:'Services',body:'Plan the next step.'},{title:'Design',url:'#design',group:'Services',body:'Make the right impression.'},{title:'Help centre',url:'#help',group:'Resources',body:'Answers and guidance.'}]}),
  widget('breadcrumb','Breadcrumb','Navigation','navigation','Ordered navigation trail marking the current page.',{title:'You are here',items:linkItems}),
  widget('pagination','Pagination','Navigation','navigation','Numbered page links using an editable page query parameter.',{title:'Pages',total:5,current:1,url:'?page='}),
  widget('previous-next','Previous / Next','Navigation','navigation','Adjacent content links with separate destinations.',{previousLabel:'Previous article',previousUrl:'#previous',nextLabel:'Next article',nextUrl:'#next'}),
  widget('anchor-navigation','Anchor Navigation','Navigation','navigation','In-page links that scroll to section IDs.',{title:'On this page',items:linkItems}),
  widget('floating-navigation','Floating Navigation','Navigation','navigation','Sticky compact anchor toolbar.',{title:'Quick access',items:linkItems,offset:12}),
  widget('sidebar-navigation','Sidebar Navigation','Navigation','navigation','Vertical grouped page links with a current-page marker.',{title:'Documentation',items:[{title:'Start here',url:'#start',group:'Introduction'},{title:'Installation',url:'#installation',group:'Introduction'},{title:'API',url:'#api',group:'Reference'}]}),
  widget('table-of-contents','Table of Contents','Navigation','navigation','Builds links from headings inside a configured content selector.',{title:'Contents',selector:'main',levels:'h2,h3'}),
  widget('language-switcher','Language Switcher','Navigation','navigation','Select a language and navigate to its configured page.',{title:'Language',items:[{title:'English',url:'/en'},{title:'Hindi',url:'/hi'}]}),

  widget('responsive-image','Responsive Image','Media','media','Picture sources for desktop and mobile with a caption.',{title:'Our workspace',image:'',mobileImage:'',alt:'A welcoming workspace',caption:'Built for collaboration.'}),
  widget('masonry-gallery','Masonry Gallery','Media','collection','Variable-height photograph columns with captions.',{title:'Our work',columns:3,items:cards}),
  widget('lightbox-gallery','Lightbox Gallery','Media','collection','Open photographs in a keyboard-dismissable full-size dialog.',{title:'Photo collection',columns:3,items:cards}),
  widget('logo-carousel','Logo Carousel','Media','carousel','Rotating partner logos with links and accessible names.',{title:'Our partners',autoplay:true,interval:4,items:[{title:'Partner one',image:'',url:'#partner-one'},{title:'Partner two',image:'',url:'#partner-two'}]}),
  widget('youtube','YouTube','Media','media','Embed a YouTube video using its public video ID.',{title:'Introduction',videoId:'aqz-KE-bpKQ',start:0}),
  widget('vimeo','Vimeo','Media','media','Embed a Vimeo video by its numeric video ID.',{title:'Our film',videoId:'76979871'}),
  widget('video-background','Video Background','Media','media','Muted looping background video with a readable editable overlay.',{title:'Make an impression',body:'Your story, in motion.',src:'',poster:'',autoplay:true}),
  widget('before-after','Before / After Image','Media','media','Compare two images using an adjustable reveal slider.',{title:'The transformation',beforeImage:'',afterImage:'',beforeAlt:'Before',afterAlt:'After',value:50}),
  widget('image-hotspot','Image Hotspot','Media','media','Position a focusable explanatory hotspot over an image.',{title:'Explore the details',image:'',alt:'Product details',x:50,y:50,body:'Learn more about this feature.'}),
  widget('image-zoom','Image Zoom','Media','media','Zoom a picture using a range control.',{title:'Look closer',image:'',alt:'Detailed view',maxZoom:3}),
  widget('media-card','Media Card','Media','media','Linked image with a media-type badge and description.',{title:'Watch our story',image:'',alt:'Video cover',body:'Discover the people behind the work.',url:'#video',mediaType:'Video'}),
  widget('audio-playlist','Audio Playlist','Media','media','Select tracks and play them in a shared native audio player.',{title:'Listen',items:[{title:'Introduction',url:''},{title:'Our story',url:''}]}),

  ...(['text','email','password','number','tel','url','search','date','time','datetime-local','color','month','week'] as const).map(kind=>widget(`input-${kind}` as const,`${({tel:'Phone','datetime-local':'Date Time'} as Record<string,string>)[kind] ?? labelFor(kind)} Input`,'Forms','input',`Native ${kind} input with labels and browser validation.`,{title:`${labelFor(kind)} field`,name:`field-${kind}`,placeholder:'',required:false,value:kind==='color'?'#6366f1':'',...(kind==='number'?{min:0,max:100,step:1}:{})})),
  widget('textarea','Textarea','Forms','input','Multi-line form text with required validation.',{title:'Your message',name:'message',placeholder:'How can we help?',required:true,rows:4,value:''}),
  widget('select','Select','Forms','input','Native single-choice dropdown.',{title:'Choose a service',name:'service',required:true,options:['Consultation','Design','Development']}),
  widget('multi-select','Multi Select','Forms','input','Native multiple selection list.',{title:'Your interests',name:'interests',required:false,options:['Design','Technology','Business']}),
  widget('checkbox','Checkbox','Forms','input','Named checkbox with editable checked value.',{title:'I agree to the terms',name:'agreement',value:'yes',required:true,checked:false}),
  widget('radio','Radio Group','Forms','input','Mutually exclusive named options.',{title:'Contact preference',name:'preference',required:true,options:['Email','Phone']}),
  widget('toggle','Toggle Switch','Forms','input','Keyboard operable on/off switch for a named form value.',{title:'Send updates',name:'updates',value:'yes',checked:false,required:false}),
  widget('range','Range Slider','Forms','input','Numeric slider with a live value readout.',{title:'Budget',name:'budget',min:0,max:1000,step:10,value:100,required:false}),
  widget('file-upload','File Upload','Forms','input','Native file picker with optional multiple file selection.',{title:'Attach files',name:'attachments',accept:'.pdf,.png,.jpg',multiple:false,required:false}),
  widget('hidden-field','Hidden Field','Forms','input','Invisible named field included in form submission.',{title:'Campaign',name:'campaign',value:'website'}),
  widget('submit-button','Submit Button','Forms','input','Submits its parent form and invokes native validation.',{label:'Send request'}),
  widget('reset-button','Reset Button','Forms','input','Restores parent form controls to their initial values.',{label:'Reset form'}),
  widget('form-container','Form Container','Forms','layout','Nest form controls and submit multipart data to your endpoint.',{title:'Your enquiry',endpoint:'',successMessage:'Your request was received.',gap:16}),
  widget('login-form','Login Form','Forms','form','Email/password form connected to a configurable authentication endpoint.',{title:'Sign in',label:'Sign in',endpoint:'',successMessage:'Signed in successfully.'}),
  widget('register-form','Register Form','Forms','form','Name, email and confirmed password with provider submission.',{title:'Create account',label:'Register',endpoint:'',successMessage:'Account created.'}),
  widget('forgot-password','Forgot Password Form','Forms','form','Request a password reset through a configured provider.',{title:'Reset password',label:'Request reset',endpoint:'',successMessage:'Check your inbox for the next step.'}),
  widget('search-form','Search Form','Forms','form','Submit a search query to a configured page using GET.',{title:'Search the website',label:'Search',url:'/search',parameter:'q'}),
  widget('multi-step-form','Multi-step Form','Forms','form','Validated contact details followed by a message and provider submission.',{title:'Tell us about your project',label:'Send enquiry',endpoint:'',successMessage:'Your enquiry was received.'}),
  widget('survey-form','Survey Form','Forms','form','Rating and feedback collection through a configurable endpoint.',{title:'How did we do?',label:'Submit feedback',endpoint:'',successMessage:'Thank you for your feedback.'}),

  widget('vertical-tabs','Vertical Tabs','Interactive','panels','Keyboard navigable tabs with a vertical tab list.',{title:'Explore',items:panels}),
  widget('drawer','Drawer','Interactive','disclosure','Side dialog with focus containment and Escape dismissal.',{title:'Quick information',label:'Open drawer',body:'Useful details without leaving this page.'}),
  widget('popover','Popover','Interactive','disclosure','Click to expand contextual content with Escape dismissal.',{title:'Helpful information',label:'Show details',body:'More context for this choice.'}),
  widget('collapse','Collapse','Interactive','disclosure','Native disclosure that expands a labelled content area.',{title:'Additional details',body:'More information is available here.'}),
  widget('toggle-content','Toggle Content','Interactive','panels','Switch between two editable content states.',{title:'Choose your view',label:'Switch view',first:'Personal plans for individuals.',second:'Business plans for teams.'}),
  widget('flip-card','Flip Card','Interactive','panels','Keyboard/click toggle between front and back card content.',{title:'Discover more',label:'Flip card',first:'An introduction to our service.',second:'A closer look at how we can help.'}),
  widget('hover-card','Hover Card','Interactive','disclosure','Profile details revealed on hover and keyboard focus.',{title:'Alex Morgan',label:'View profile',body:'Designer and customer advocate.'}),
  widget('reveal','Scroll Reveal','Interactive','disclosure','Reveal editable content as it enters the viewport.',{title:'A fresh perspective',body:'Content revealed as you scroll.',duration:600}),
  widget('timer','Timer','Interactive','timer','Start, pause and reset a duration countdown.',{title:'Focus session',seconds:300}),
  widget('stopwatch','Stopwatch','Interactive','timer','Measure elapsed time with pause and reset.',{title:'Elapsed time'}),
  widget('scroll-progress','Scroll Progress','Interactive','metric','Tracks scroll completion of the nearest scrollable page area.',{title:'Reading progress'}),
  widget('read-more','Read More','Interactive','collection','Expand a longer article beyond an editable preview length.',{title:'Our story',body:'We began with a simple idea: make quality work accessible. Today our team helps organisations plan, build and grow. We believe clear communication and thoughtful design make the difference. Every project starts with listening and ends with work we can stand behind.',limit:100,label:'Read more'}),
  widget('load-more','Load More','Interactive','collection','Progressively reveal more cards without a backend.',{title:'Discover our work',batch:1,label:'Load more',items:cards}),
  widget('cookie-consent','Cookie Consent','Interactive','disclosure','Store a visitor choice locally; does not itself block external scripts.',{title:'Privacy preferences',body:'Allow optional cookies?',label:'Accept',rejectLabel:'Decline',storageKey:'site-cookie-choice'}),

  widget('feature-box','Feature Box','Marketing','cards','Icon-led feature with editable benefit and destination.',{title:'Built around you',body:'Flexible options tailored to your goals.',icon:'Zap',url:'#features',label:'Explore'}),
  widget('service-card','Service Card','Business','cards','Service description, duration and enquiry action.',{title:'Design consultation',body:'Expert guidance for your next project.',duration:'60 minutes',price:'From $80',url:'#contact',label:'Enquire'}),
  widget('services-grid','Services Grid','Business','collection','Editable services with descriptions and individual links.',{title:'Our services',columns:3,items:cards}),
  widget('pricing-card','Pricing Card','Marketing','cards','Single plan with price, billing period and editable features.',{title:'Professional',price:29,currency:'USD',period:'month',items:['Five projects','Priority support','Custom domain'],url:'#signup',label:'Choose plan'}),
  widget('pricing-toggle','Pricing Toggle','Marketing','metric','Switch between monthly and annual prices and billing labels.',{title:'Professional plan',monthly:29,annual:290,currency:'USD',url:'#signup',label:'Choose plan'}),
  widget('testimonial','Testimonial','Business','cards','Customer quotation with attribution, role and portrait.',{title:'Customer story',body:'The team made every step clear and delivered excellent work.',name:'Alex Morgan',role:'Business owner',image:'',rating:5}),
  widget('testimonial-carousel','Testimonial Carousel','Business','carousel','Rotate editable customer quotes and attribution.',{title:'Customer stories',autoplay:false,interval:6,items:[{title:'Alex Morgan',body:'A thoughtful team and excellent results.',role:'Founder',image:''},{title:'Sam Lee',body:'Clear communication from start to finish.',role:'Director',image:''}]}),
  widget('team-member','Team Member','Business','cards','Staff portrait, biography, role and contact link.',{title:'Alex Morgan',role:'Creative director',body:'Turning ideas into useful experiences.',image:'',url:'mailto:alex@example.com',label:'Contact Alex'}),
  widget('timeline','Timeline','Business','collection','Chronological events with dates and editable descriptions.',{title:'Our journey',items:[{title:'The beginning',date:'2020',body:'We opened our first studio.'},{title:'Growing together',date:'2026',body:'Working with customers around the world.'}]}),
  widget('process','Process','Business','collection','Numbered workflow with duration and a clear outcome.',{title:'How we work',items:[{title:'Discover',body:'Understand your goals.',duration:'1 week'},{title:'Build',body:'Create and review the solution.',duration:'3 weeks'}]}),
  widget('comparison-table','Comparison Table','Marketing','table','Feature comparison with named columns and editable cells.',{title:'Compare plans',columns:['Feature','Starter','Professional'],rows:[{title:'Projects',cells:'1 | 5'},{title:'Support',cells:'Email | Priority'}]}),
  widget('trust-badges','Trust Badges','Marketing','collection','Editable credentials with explanatory text and verification links.',{title:'Our commitments',columns:3,items:[{title:'Secure handling',body:'Learn how we protect your information.',url:'#privacy',image:''},{title:'Personal support',body:'Talk to a real member of the team.',url:'#support',image:''}]}),
  widget('promo-banner','Promo Banner','Marketing','cards','Promotion with coupon copy action and destination.',{title:'A welcome offer',body:'Save on your first purchase.',code:'WELCOME10',url:'#shop',label:'Shop now'}),
  widget('business-card','Business Card','Business','cards','Business identity with clickable phone, email and address.',{title:'North Studio',body:'Design and strategy for growing businesses.',phone:'+1 555 0100',email:'hello@example.com',address:'12 Market Street'}),
  widget('appointment-request','Appointment Request','Business','form','Validated preferred date, contact and service enquiry; availability requires a provider.',{title:'Request an appointment',label:'Request appointment',endpoint:'',successMessage:'Your request was received. We will confirm availability.'}),

  widget('blog-card','Blog Card','Blog','cards','Linked article preview with author, date and category.',article),
  widget('blog-grid','Blog Grid','Blog','collection','Responsive grid of editable article records.',{title:'Latest stories',columns:3,items:[article,{...article,title:'Design with purpose',category:'Design'}]}),
  widget('post-list','Post List','Blog','collection','Compact article rows with date and excerpt.',{title:'All articles',items:[article,{...article,title:'A thoughtful process'}]}),
  widget('featured-post','Featured Post','Blog','cards','Lead article with large image, excerpt and reading link.',{...article,label:'Read the feature'}),
  widget('author-box','Author Box','Blog','cards','Author portrait, biography and profile link.',{title:'Alex Morgan',role:'Editor',body:'Writing about design and the web.',image:'',url:'#author',label:'More by Alex'}),
  widget('post-meta','Post Meta','Blog','text','Semantic publication date, author and category.',{author:'Alex Morgan',date:'2026-09-15',category:'Guides',url:'#guides'}),
  widget('category-list','Category List','Blog','navigation','Category destinations with editable article counts.',{title:'Categories',items:[{title:'Guides',url:'#guides',count:12},{title:'News',url:'#news',count:8}]}),
  widget('tags','Tags','Blog','navigation','Compact tag links for related content discovery.',{title:'Topics',items:[{title:'Design',url:'#design'},{title:'Technology',url:'#technology'}]}),
  widget('related-posts','Related Posts','Blog','collection','Curated related articles with editable descriptions.',{title:'You may also enjoy',columns:3,items:[article]}),
  widget('comments-ui','Comments','Blog','form','Editable comment list and provider-backed new comment form.',{title:'Discussion',label:'Post comment',endpoint:'',successMessage:'Your comment was received.',items:[{name:'Alex',body:'Thanks for sharing this useful guide.'}]}),
  widget('search-results','Search Results','Blog','collection','Filter local article records using the URL query and a search box.',{title:'Search results',parameter:'q',items:[article,{...article,title:'Getting started',category:'Help'}]}),
  widget('archive-list','Archive List','Blog','navigation','Links to dated archives with article counts.',{title:'Archives',items:[{title:'September 2026',url:'?month=2026-09',count:6},{title:'August 2026',url:'?month=2026-08',count:4}]}),
  widget('social-share','Social Share','Blog','action','Share a configured article using platform share URLs.',{title:'Share this article',url:'',text:'A useful article',platforms:['Facebook','LinkedIn','X','Email']}),
  widget('reading-time','Reading Time','Blog','metric','Estimate reading minutes from a selected article element.',{title:'Reading time',selector:'main',wordsPerMinute:200}),

  widget('product-card','Product Card','Ecommerce','commerce','Product details with a local-cart add action.',product),
  widget('product-grid','Product Grid','Ecommerce','commerce','Responsive product records with independent add-to-cart actions.',{title:'Shop the collection',columns:3,items:[product,{...product,productId:'product-2',title:'Daily planner',price:32}]}),
  widget('product-list','Product List','Ecommerce','commerce','Compact purchasable product rows with descriptions.',{title:'All products',items:[product]}),
  widget('product-gallery','Product Gallery','Ecommerce','carousel','Navigate product photographs and captions.',{title:'Product views',autoplay:false,interval:5,items:[{title:'Front view',image:'',body:'The front cover.'},{title:'Inside',image:'',body:'Pages for your ideas.'}]}),
  widget('product-title','Product Title','Ecommerce','text','Semantic product heading with an editable SKU.',{title:'Everyday notebook',sku:'NOTE-001'}),
  widget('product-price','Product Price','Ecommerce','metric','Format a product price in the configured currency.',{title:'Price',value:24,currency:'USD'}),
  widget('sale-price','Sale Price','Ecommerce','metric','Original and sale prices with calculated savings.',{title:'Special price',original:30,value:24,currency:'USD'}),
  widget('product-rating','Product Rating','Ecommerce','metric','Read-only rating summary with review count and review link.',{title:'Customer rating',value:4.5,max:5,count:24,url:'#reviews'}),
  widget('quantity-selector','Quantity Selector','Ecommerce','commerce','Increment/decrement a bounded purchase quantity.',{title:'Quantity',min:1,max:20,value:1}),
  widget('add-to-cart','Add To Cart','Ecommerce','commerce','Add a configured product to the shared local cart.',{...product,label:'Add to cart',quantity:1}),
  widget('buy-now','Buy Now','Ecommerce','commerce','Send a configured product to a checkout provider; no payment is simulated.',{...product,label:'Buy now',quantity:1,endpoint:''}),
  widget('product-tabs','Product Tabs','Ecommerce','panels','Switch product description, specification and shipping panels.',{title:'Product details',items:[{title:'Description',body:'A durable notebook for everyday ideas.'},{title:'Specifications',body:'A5 size. 160 pages.'},{title:'Shipping',body:'Shipping is calculated by your checkout provider.'}]}),
  widget('product-description','Product Description','Ecommerce','text','Formatted product copy and specifications list.',{title:'About this product',body:'Designed for everyday use.',items:['A5 format','160 lined pages','Durable cover']}),
  widget('product-variations','Product Variations','Ecommerce','commerce','Choose a product option and add its own SKU/price to the cart.',{title:'Choose an option',currency:'USD',items:[{title:'Small',productId:'notebook-small',price:18},{title:'Large',productId:'notebook-large',price:24}]}),
  widget('product-badge','Product Badge','Ecommerce','text','Availability badge with stock count and status.',{title:'In stock',stock:12}),
  widget('category-card','Product Category','Ecommerce','cards','Linked collection cover with product count.',{title:'Notebooks',image:'',body:'Make room for your ideas.',count:12,url:'#notebooks',label:'Browse collection'}),
  widget('category-grid','Product Categories','Ecommerce','collection','Collection covers with separate destinations and counts.',{title:'Browse categories',columns:3,items:[{title:'Notebooks',image:'',url:'#notebooks',count:12},{title:'Accessories',image:'',url:'#accessories',count:8}]}),
  widget('cart-item','Cart Item','Ecommerce','commerce','View and remove a configured SKU from the shared cart.',{title:'Selected product',productId:'product-1',currency:'USD'}),
  widget('cart-summary','Cart Summary','Ecommerce','commerce','Live local-cart quantity and subtotal, with provider checkout.',{title:'Your order',currency:'USD',endpoint:'',label:'Continue to checkout'}),
  widget('mini-cart','Mini Cart','Ecommerce','commerce','Expandable live cart with quantities and remove controls.',{title:'Shopping cart',currency:'USD',label:'View cart'}),
  widget('checkout-form','Checkout Form','Ecommerce','form','Validated customer/address form sent with the local cart to a checkout provider.',{title:'Checkout details',label:'Continue to secure checkout',endpoint:'',successMessage:'Checkout request received.'}),
  widget('coupon','Coupon','Ecommerce','form','Validate a coupon against a provider instead of inventing a discount.',{title:'Have a coupon?',label:'Apply coupon',endpoint:'',successMessage:'Coupon accepted.'}),
  widget('wishlist','Wishlist Button','Ecommerce','commerce','Toggle a product in a browser-local wishlist.',{...product,label:'Save to wishlist'}),
  widget('compare-product','Compare Product','Ecommerce','commerce','Toggle a product in the local comparison selection.',{...product,label:'Add to comparison'}),
  widget('related-products','Related Products','Ecommerce','commerce','Curated complementary products with cart actions.',{title:'Pairs well with',columns:3,items:[{...product,productId:'accessory-1',title:'Pen set',price:12}]}),

  ...(['facebook','instagram','linkedin','twitter','telegram','pinterest','tiktok','discord','github','reddit','snapchat','youtube'] as const).map(platform=>widget(`${platform}-link` as const,`${platform==='twitter'?'X / Twitter':labelFor(platform)} Link`,'Social','action',`Open an editable ${platform} profile or destination.`,{label:`Follow on ${platform==='twitter'?'X':labelFor(platform)}`,url:`https://${platform==='twitter'?'x':platform==='telegram'?'t':platform}.`+(platform==='telegram'?'me/':'com/'),newTab:true})),
  widget('email-share','Email Share','Social','action','Open an email draft with subject and body.',{label:'Share by email',subject:'Take a look',body:'I thought you might like this.',url:''}),
  widget('follow-buttons','Follow Buttons','Social','navigation','Editable social profile links with platform names.',{title:'Follow our work',items:[{title:'Instagram',url:'https://instagram.com/'},{title:'LinkedIn',url:'https://linkedin.com/'}]}),

  widget('data-table','Data Table','Data','table','Search, sort and paginate editable table rows.',{title:'Team directory',columns:['Name','Team','Location'],rows:[{title:'Alex Morgan',cells:'Design | London'},{title:'Sam Lee',cells:'Engineering | Delhi'},{title:'Jamie Reed',cells:'Support | Paris'}],pageSize:5}),
  ...(['bar','line','pie','doughnut'] as const).map(kind=>widget(`${kind}-chart` as const,`${labelFor(kind)} Chart`,'Data','chart',`Accessible ${kind} chart from editable numeric records.`,{title:'Monthly results',items:[{title:'January',value:30},{title:'February',value:50},{title:'March',value:40}]})),
  widget('json-viewer','JSON Viewer','Data','data','Parse JSON into an expandable tree with invalid-data feedback.',{title:'Structured data',json:'{"name":"North Studio","services":["Design","Development"],"active":true}'}),
  widget('iframe','Iframe','Advanced','media','Sandboxed external frame with title and adjustable height.',{title:'Embedded resource',url:'https://example.com',height:320}),
  widget('custom-code','Custom Code','Advanced','data','Execute explicit HTML/CSS/JS in an isolated opaque-origin sandbox.',{title:'Interactive embed',code:'<button onclick="this.textContent=\'Clicked\'">Try me</button>',height:180}),
  widget('search-widget','Search Widget','Advanced','collection','Search editable records locally without requiring an external index.',{title:'Find a resource',items:[article,{...article,title:'Contact our team',category:'Support'}]}),
  widget('progress-tracker','Progress Tracker','Data','data','Check milestones and calculate completion locally.',{title:'Project checklist',items:['Brief approved','Design reviewed','Website launched']}),
  widget('stepper','Stepper','Data','panels','Move through named steps with previous/next controls.',{title:'Your next steps',items:panels}),
  widget('calendar','Calendar','Data','data','Navigate months and select a date; no availability is implied.',{title:'Choose a date',startDate:'2026-09-15'}),
  widget('calculator','Calculator','Data','data','Perform arithmetic on two numbers without evaluating code.',{title:'Quick calculation',first:10,second:5}),
  widget('unit-converter','Unit Converter','Data','data','Convert length between metres, kilometres, miles and feet.',{title:'Length converter',value:1}),
  widget('percentage-calculator','Percentage Calculator','Data','data','Calculate a percentage of an editable amount.',{title:'Percentage calculator',value:200,percent:15}),
  widget('file-downloads','File Downloads','Advanced','navigation','Download list with filenames, formats and editable destinations.',{title:'Resources',items:[{title:'Brochure',url:'/brochure.pdf',format:'PDF',filename:'brochure.pdf'},{title:'Price list',url:'/prices.pdf',format:'PDF',filename:'prices.pdf'}]}),

  widget('job-openings','Job Openings','Business','collection','Current roles with a short description and an apply link for each.',{title:'Open positions',columns:2,items:[{title:'Marketing Coordinator',body:'Full-time · Remote',url:'#apply-marketing'},{title:'Support Specialist',body:'Part-time · On-site',url:'#apply-support'}]}),
  widget('press-mentions','Press Mentions','Marketing','collection','Coverage from press and media, each with a quote and a link to the piece.',{title:'As featured in',columns:3,items:[{title:'Daily Business Journal',body:'"A refreshingly simple way to get online."',image:'',url:'#press-1'},{title:'Weekly Trade Review',body:'"Exactly what small teams need."',image:'',url:'#press-2'}]}),
  widget('client-logos','Client Logos','Business','collection','A static grid of client or partner logos, each linking to their site.',{title:'Trusted by',columns:4,items:[{title:'Northwind Traders',image:'',url:'#'},{title:'Acme Studio',image:'',url:'#'},{title:'Blue Harbor',image:'',url:'#'}]}),
  widget('awards-list','Awards & Recognition','Business','collection','Awards and credentials with the year they were received.',{title:'Awards & recognition',columns:3,items:[{title:'Best Local Service 2025',body:'Awarded by the Chamber of Commerce.',date:'2025'},{title:'Excellence in Customer Care',body:'Recognised for outstanding support.',date:'2024'}]}),
  widget('upcoming-events','Upcoming Events','Marketing','collection','Dated events with a description and an RSVP or details link.',{title:'Upcoming events',columns:2,items:[{title:'Open House',body:'Meet the team and tour our space.',date:'2026-10-04',url:'#rsvp-open-house'},{title:'Community Workshop',body:'A free hands-on session for beginners.',date:'2026-11-12',url:'#rsvp-workshop'}]}),
  widget('use-cases','Use Cases','Marketing','collection','Who the product is for, grouped as short editable scenarios.',{title:'Built for how you work',columns:3,items:[{title:'Solo founders',body:'Launch a professional site without a developer.',image:'',url:'#solo'},{title:'Growing teams',body:'Keep every page consistent as you scale.',image:'',url:'#teams'}]}),
  widget('integrations-grid','Integrations','Marketing','collection','Tools and platforms the product connects with, each with its own link.',{title:'Works with your tools',columns:4,items:[{title:'Google Workspace',image:'',url:'#'},{title:'Slack',image:'',url:'#'},{title:'Zapier',image:'',url:'#'}]}),

  widget('service-areas','Service Areas','Business','navigation','Locations or districts the business serves, each linking to more detail.',{title:'Where we work',items:[{title:'Downtown',url:'#downtown'},{title:'Riverside',url:'#riverside'},{title:'Uptown',url:'#uptown'}]}),
  widget('partner-directory','Partner Directory','Business','navigation','A directory of partners or affiliates grouped by type, each with its own link.',{title:'Our partners',items:[{title:'Northwind Traders',url:'#',group:'Suppliers'},{title:'Blue Harbor Logistics',url:'#',group:'Logistics'}]}),
  widget('site-map','Sitemap','Navigation','navigation','A grouped list of every page, useful to visitors and search engines alike.',{title:'Sitemap',items:[{title:'Home',url:'/',group:'Main'},{title:'About',url:'/about',group:'Main'},{title:'Contact',url:'/contact',group:'Main'}]}),

  widget('rsvp-form','RSVP Form','Business','form','Collects a name, email and any notes for an event, sent to your configured provider.',{title:'RSVP',label:'Send RSVP',endpoint:'',successMessage:'Thanks — your RSVP was received.'}),
  widget('job-application-form','Job Application Form','Business','form','Collects a name, email and a short note for an opening, sent to your configured provider.',{title:'Apply for this role',label:'Submit application',endpoint:'',successMessage:'Thanks — your application was received.'}),

  widget('live-clock','Live Clock','Data','data','Shows the visitor local date and time, updating every second.',{title:'Current time'}),
  widget('typewriter-text','Typewriter Text','Interactive','data','Animates a line of text as if it is being typed, respecting reduced motion.',{body:'Building something great, one page at a time.',speed:40}),
  widget('marquee-text','Marquee Text','Marketing','data','A continuously scrolling announcement line, paused for reduced motion.',{body:'New: free shipping on orders over $50 — Extended hours this weekend — Now booking for December.'}),
  widget('random-quote','Random Quote','Interactive','data','Shows one editable quote at a time, with a button to show another at random.',{items:[{quote:'Do simple things with great care.',author:'—'},{quote:'Consistency beats intensity.',author:'—'},{quote:'Every page is a chance to earn trust.',author:'—'}]}),
  widget('poll-widget','Poll','Interactive','data','A single-choice poll that sends the selected option to a configured provider.',{title:'Quick poll',items:['Option A','Option B','Option C'],endpoint:'',successMessage:'Thanks for voting!'}),
  widget('sortable-list','Sortable List','Interactive','data','A checklist visitors can reorder with up/down controls, fully keyboard operable.',{title:'Our checklist',items:['Confirm your details','Choose a plan','Invite your team']}),
  widget('speed-dial','Speed Dial','Interactive','disclosure','A floating button that expands into a short list of quick actions.',{label:'Quick actions',items:[{title:'Call us',url:'tel:+10000000000'},{title:'Email us',url:'mailto:hello@example.com'},{title:'WhatsApp',url:'https://wa.me/10000000000'}]}),
  widget('scroll-spy-nav','Scroll Spy Navigation','Navigation','navigation','In-page links that highlight the section currently in view as visitors scroll.',{title:'On this page',items:[{title:'Overview',url:'#overview'},{title:'Details',url:'#details'},{title:'Contact',url:'#contact'}]}),
  widget('exit-intent-popup','Exit Intent Popup','Marketing','disclosure','Opens automatically once, the first time a visitor moves to leave the page.',{title:'Before you go',body:'Leave your email and we will send you our latest updates.',label:'Show offer'}),
  widget('sticky-cta-bar','Sticky CTA Bar','Marketing','disclosure','A dismissible bar fixed to the bottom of the screen with one call to action.',{body:'Limited-time offer — book this week and save.',label:'Claim offer',url:'#offer'}),
  widget('currency-converter','Currency Converter','Data','data','Converts an amount between major currencies using illustrative rates.',{title:'Currency converter',value:100}),
  widget('age-calculator','Age Calculator','Data','data','Calculates exact age in years, months and days from a date of birth.',{title:'Age calculator',birthdate:'2000-01-01'}),
  widget('bmi-calculator','BMI Calculator','Data','data','Calculates body mass index and its category from height and weight.',{title:'BMI calculator',heightCm:170,weightKg:70}),
  widget('tip-calculator','Tip Calculator','Data','data','Splits a bill with tip across a number of people.',{title:'Tip calculator',bill:50,tipPercent:15,people:1}),
  widget('loan-calculator','Loan Calculator','Data','data','Estimates a monthly loan payment from the amount, rate and term.',{title:'Loan calculator',principal:200000,annualRate:6.5,years:20}),
  widget('donation-progress','Donation Progress','Business','data','A fundraising goal and amount raised so far, shown as a progress bar you update.',{title:'Help us reach our goal',goal:10000,raised:6400,currency:'USD'}),

  widget('card-container','Card Container','Layout','layout','A bordered, shadowed card that groups its child widgets together.',{title:'Card',gap:16}),
  widget('centered-container','Centered Container','Layout','layout','Keeps children inside a maximum width, centred on the page.',{title:'Centered content',maxWidth:720,gap:16}),
  widget('full-height-section','Full Height Section','Layout','layout','A section that fills the screen height with vertically centred children.',{title:'Full height section',gap:24}),
  widget('bleed-section','Full Bleed Section','Layout','layout','Breaks out of the page width to fill the screen edge to edge.',{title:'Full width section',gap:24}),
  widget('divider-with-text','Divider with Text','Layout','text','A horizontal rule with a short editable label in the middle, such as "OR".',{body:'OR'}),

  widget('mobile-menu','Mobile Menu','Navigation','disclosure','A menu button that opens a full navigation panel, for small screens.',{label:'Menu',items:linkItems}),
  widget('page-tabs','Page Tabs','Navigation','navigation','A horizontal row of page links styled as tabs.',{title:'Sections',items:linkItems}),
  widget('link-in-bio','Link in Bio','Navigation','navigation','A single stacked list of large link buttons, for a profile or bio page.',{title:'Find us',items:[{title:'Visit our website',url:'#'},{title:'Book an appointment',url:'#'},{title:'Message us',url:'#'}]}),

  widget('pdf-viewer','PDF Viewer','Media','media','An embedded PDF document with a fallback download link.',{title:'Document',url:'',height:600}),
  widget('video-playlist','Video Playlist','Media','media','Select clips and play them in a shared native video player.',{title:'Watch',items:[{title:'Introduction',url:''},{title:'Behind the scenes',url:''}]}),
  widget('gallery-filter','Filterable Gallery','Media','collection','A photo grid with category buttons that filter which photos show.',{title:'Our work',columns:3,items:[{title:'Kitchen remodel',image:'',category:'Interiors'},{title:'Garden path',image:'',category:'Outdoors'},{title:'Living room',image:'',category:'Interiors'}]}),

  widget('signature-pad','Signature Pad','Forms','data','Captures a drawn signature with the mouse, finger or stylus, with a clear button.',{title:'Sign here'}),
  widget('otp-input','Verification Code Input','Forms','data','A row of single-character boxes for a one-time code, with automatic focus advance.',{title:'Enter the 6-digit code',length:6}),
  widget('dual-range-slider','Range Slider (Min–Max)','Forms','data','Two handles for choosing a minimum and maximum value, such as a price range.',{title:'Price range',min:0,max:1000,valueMin:100,valueMax:600}),

  widget('like-button','Like Button','Interactive','data','A toggleable like button that remembers the visitor choice in this browser.',{label:'Like this'}),
  widget('image-lightbox-single','Single Image Lightbox','Interactive','media','One image that opens full-size in a keyboard-dismissable dialog when clicked.',{title:'View the full diagram',image:'',alt:'Detailed diagram'}),
  widget('emoji-reactions','Emoji Reactions','Interactive','data','Editable emoji buttons that send the visitor choice to a configured provider.',{items:['👍','❤️','🎉'],endpoint:'',successMessage:'Thanks for reacting!'}),

  widget('office-locations','Office Locations','Business','collection','Multiple business locations, each with an address and a map link.',{title:'Find a location near you',columns:2,items:[{title:'Downtown office',body:'12 Market Street',url:'#map-downtown'},{title:'Riverside office',body:'48 River Road',url:'#map-riverside'}]}),
  widget('service-price-list','Service Price List','Business','table','A simple two-column list of services and their prices.',{title:'Our prices',columns:['Service','Price'],rows:[{title:'Consultation',cells:'$50'},{title:'Full session',cells:'$120'}]}),

  widget('content-upgrade-form','Content Upgrade Form','Blog','form','Offers a downloadable extra in exchange for an email address, sent to your provider.',{title:'Get the free checklist',label:'Send it to me',endpoint:'',successMessage:'Check your inbox for the download link.'}),
  widget('was-this-helpful','Was This Helpful','Blog','data','A quick yes/no feedback control that sends the answer to a configured provider.',{title:'Was this article helpful?',endpoint:''}),

  widget('free-shipping-progress','Free Shipping Progress','Ecommerce','commerce','Shows how close the shared cart is to a configured free-shipping threshold.',{title:'Free shipping',threshold:75,currency:'USD'}),
  widget('size-guide','Size Guide','Ecommerce','disclosure','A button that opens a size chart in a dialog.',{title:'Size guide',label:'Size guide',columns:['Size','Chest','Waist'],rows:[{title:'S',cells:'36 | 30'},{title:'M',cells:'40 | 34'},{title:'L',cells:'44 | 38'}]}),
  widget('low-stock-alert','Low Stock Alert','Ecommerce','text','Shows an urgency message only once stock falls below a configured threshold.',{stock:3,threshold:5}),
  widget('back-in-stock-form','Back in Stock Form','Ecommerce','form','Collects an email to notify a visitor when a product is available again.',{title:'Notify me when back in stock',label:'Notify me',endpoint:'',successMessage:'We will let you know.'}),
  widget('gift-message','Gift Message','Ecommerce','input','A multi-line note field a customer can add to their order.',{title:'Add a gift message',name:'giftMessage',placeholder:'Write a short note…',required:false}),
  widget('product-inquiry-form','Product Inquiry Form','Ecommerce','form','Asks about a custom or quote-only product, sent to your configured provider.',{title:'Ask about this product',label:'Send inquiry',endpoint:'',successMessage:'Thanks — we will get back to you.'}),
  widget('wishlist-summary','Wishlist Summary','Ecommerce','commerce','Lists every product currently saved to the shared local wishlist.',{title:'Your saved items',currency:'USD'}),

  widget('whatsapp-share','WhatsApp Share','Social','action','Shares the current page through WhatsApp.',{label:'Share on WhatsApp',text:'Take a look at this'}),
  widget('sms-share','SMS Share','Social','action','Shares the current page through a text message.',{label:'Share by text',text:'Take a look at this'}),

  widget('date-calculator','Date Difference Calculator','Data','data','Counts the days, weeks and months between two chosen dates.',{title:'Date calculator'}),
  widget('random-number-generator','Random Number Generator','Data','data','Generates a random whole number within an editable range.',{title:'Random number',min:1,max:100}),
  widget('text-case-converter','Text Case Converter','Data','data','Converts pasted text to upper case, lower case or title case.',{title:'Text case converter'}),
  widget('simple-quiz','Simple Quiz','Data','data','A single multiple-choice question that checks the answer locally.',{title:'Quick quiz',question:'What does WWW stand for?',options:['World Wide Web','World Wide Wire','Wide World Web'],correctIndex:0}),
  widget('color-picker-tool','Color Picker Tool','Data','data','A colour picker that shows the chosen colour as a hex code, ready to copy.',{title:'Pick a colour',value:'#6366f1'}),
  widget('roman-numeral-converter','Roman Numeral Converter','Data','data','Converts a whole number to and from Roman numerals.',{title:'Roman numeral converter',value:1994}),
  widget('percentage-change-calculator','Percentage Change Calculator','Data','data','Calculates the percentage increase or decrease between two numbers.',{title:'Percentage change',from:100,to:120}),
  widget('bmr-calculator','BMR Calculator','Data','data','Estimates daily calorie needs at rest from age, height, weight and sex.',{title:'BMR calculator',age:30,heightCm:170,weightKg:70,sex:'female'}),
  widget('interest-calculator','Interest Calculator','Data','data','Projects the future value of a deposit with simple or compound interest.',{title:'Interest calculator',principal:1000,annualRate:5,years:5,compound:true}),
  widget('random-color-generator','Random Color Generator','Data','data','Generates a random colour swatch with its hex code, ready to copy.',{title:'Random colour'}),

  widget('password-generator','Password Generator','Advanced','data','Generates a random password of a chosen length, ready to copy.',{title:'Password generator',length:16}),
  widget('print-button','Print Button','Advanced','data','Opens the browser print dialog for the current page.',{label:'Print this page'}),
  widget('share-page-button','Share Page Button','Advanced','data','Uses the device share sheet where available, or copies the page link.',{label:'Share this page'}),
  widget('course-card','Course Card','Education','cards','A course with its level, length, fee and an enrol link.',{title:'Introduction to Design',body:'A practical first course for beginners.',duration:'8 weeks',price:'$120',image:'',url:'#admissions',label:'Enrol now'}),
  widget('teacher-card','Teacher Card','Education','cards','A teacher or tutor with their subject and a short biography.',{title:'Jordan Lee',role:'Senior tutor, Mathematics',body:'Twenty years of helping students succeed.',image:'',url:'#contact',label:'Meet Jordan'}),
  widget('subjects','Subjects','Education','collection','The subjects or programmes offered, each with a short description.',{title:'What we teach',columns:3,items:[{title:'Mathematics',body:'From foundations to advanced problem solving.',url:'#'},{title:'Science',body:'Hands-on experiments and clear explanations.',url:'#'},{title:'Languages',body:'Speaking, reading and writing with confidence.',url:'#'}]}),
  widget('admissions-cta','Admissions CTA','Education','cards','A call to apply, with the admissions deadline and an apply button.',{title:'Admissions are open',body:'Applications close on 30 June. Places are limited.',url:'#apply',label:'Apply now'}),
  widget('school-events','School Events','Education','collection','Dated school events such as open days, exams and holidays.',{title:'Events and dates',columns:2,items:[{title:'Open day',body:'Visit the school and meet the teachers.',date:'2026-11-08',url:'#'},{title:'Term begins',body:'The new term starts for all classes.',date:'2027-01-12',url:'#'}]}),
] as const

export type ExpandedWidgetType = typeof expandedWidgets[number]['type']
export const layoutTypes = new Set<string>(expandedWidgets.filter(widget=>widget.family==='layout').map(widget=>widget.type))
